# Generated by Django 4.0.6 on 2022-08-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('North America', 'Northamerica'), ('South America', 'Southamerica'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('North Asia', 'Northasia'), ('South Asia', 'Southasia')], max_length=64)),
                ('text', models.CharField(max_length=64)),
                ('author', models.ManyToManyField(related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.new')),
            ],
        ),
    ]
