# Generated by Django 4.0.6 on 2022-08-12 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 12, 6, 25, 18, 430911, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
