# Generated by Django 4.0.6 on 2022-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_delete_reportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
