# Generated by Django 4.0.6 on 2022-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_user_report_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='report',
            field=models.CharField(default='No report yet.', max_length=256),
        ),
    ]
